version: '3.9'
networks:
    frontend:
        driver: bridge
services:
    php:
        build: ./docker/php
        container_name: ${PROJECT_NAME}-php
        env_file: ./.env
        environment:
            - GIT_USER_EMAIL=${GIT_USER_EMAIL}
            - GIT_USER_NAME=${GIT_USER_NAME}
        volumes:
            - ./:/var/www
        ports:
            - 8000:8000
        networks:
            - frontend